### PR TITLE
[README] Added more description and gitignore options

### PR DESCRIPTION
**Pull request by marshallshen**
Background: I pulled down the project and briefly tested out the code. Added more files in gitignore for convenience of other people. Added descriptions of absolute value functions for a more comprehensive reference.

### CODE REVIEW

**Comment by brainopia** [comment]
Heh, I prefer to keep specific to environment rules for gitignore in `.git/info/exclude` or `~/.gitignore` depending on their nature. But since we already have a lot of such rules in our .gitignore file (@eregon I'm looking at you :smirk:) it's okay to add more :wink:

The second commit I have some concerns. I think it's already assumed user can do anything with the resulting value including converting it to absolute value. So by mentioning `Numeric#abs` we're in fact documenting ruby not our library. So what purpose does it serve?

**Comment by eregon** [comment]
@brainopia Ah, indeed it seems I messed the .gitignore quite a lot while learning git (in my defense I did not know about info/exclude and ~/.gitignore). So now it is cleaned up. But you are no innocent :smirk:

**Comment by brainopia** [comment]
:scream:

**Comment by marshallshen** [comment]
@brainopia I am trying to use absolute value for some of my equations and noticed that symbolic doesn't provide abs but instead used abs from Ruby library. I agree that it is not a documentation of symbolic library and will close the pull request if that's not what you need. 

But still I will try to look into symbolic and document more stuff, I think it's a pretty cool project ;)

**Comment by brainopia** [comment]
Thanks for understanding and support! :heart:

**Pull request closed without merging**
